name: CI

on: 

  workflows_dispatch:

  push:
    branches:
      - master

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: |
      node -v
      npm -v
      python --version
      java --version
      go version
      mvn -version
      docker version
      docker-compose -v
      git version
